name: imc_tasks_manager
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_slidable: ^4.0.0
  intl: ^0.20.2
  provider: ^6.1.5
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/balance_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/balance_icon.png
